name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Rust Toolchain for GitHub CI
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: ""

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
