name: Code Coverage

on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: codecov hnsm
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: redis
        run: redis-server --appendonly no --dir tests/S288c/ &

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --bins --tests --follow-exec --engine llvm --out xml -- --test-threads 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
