name: Publish

on:
  push:
    tags:
      - '*'

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - name: Show GLIBC
        run: ldd --version
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Build
        run: cargo build --verbose --release
      - name: Create tarball
        run: tar cvfz hnsm.tar.gz target/release/hnsm target/release/fasr
        shell: bash
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hnsm.tar.gz
          asset_name: hnsm-x86_64-unknown-linux-gnu.tar.gz
          tag: ${{ github.ref }}
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.12
        run: cargo build --verbose --release
      - name: Create tarball
        run: tar cvfz hnsm.tar.gz target/release/hnsm target/release/fasr
        shell: bash
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hnsm.tar.gz
          asset_name: hnsm-x86_64-apple-darwin.tar.gz
          tag: ${{ github.ref }}
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Build
        run: cargo build --verbose --release
      - name: Create zip
        run: Compress-Archive -DestinationPath ./hnsm.zip -Path ./target/release/hnsm.exe,./target/release/fasr.exe
        shell: powershell
      - name: Upload binaries to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hnsm.zip
          asset_name: hnsm-x86_64-pc-windows-msvc.zip
          tag: ${{ github.ref }}
